# Generated by Django 5.2.5 on 2025-09-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MominKart', '0002_laptop_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='laptops/'),
        ),
    ]
