# Generated by Django 5.2.5 on 2025-09-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MominKart', '0004_watch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Watchs/'),
        ),
    ]
